services:
  - type: web
    name: automart-backend
    env: node
    region: singapore
    plan: free
    # Backend terletak di subfolder automart-backend
    rootDir: automart-backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: /api/v1
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        sync: false # Diisi manual via Dashboard Render (Supabase Connection String)
      - key: DIRECT_URL
        sync: false # Diisi manual via Dashboard Render (Supabase Direct String)
      - key: JWT_SECRET
        generateValue: true # Render akan men-generate random secure secret secara otomatis
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: STORAGE_PROVIDER
        value: cloudinary
