import { BodyType, FuelType, TransmissionType, Vehicle } from '@/types';

export const VEHICLE_MAKES = [
  'Audi',
  'BMW',
  'Chevrolet',
  'Ford',
  'Honda',
  'Hyundai',
  'Mercedes-Benz',
  'Nissan',
  'Porsche',
  'Tesla',
  'Toyota',
  'Volvo',
] as const;

export const BODY_TYPES: BodyType[] = [
  'SUV',
  'Sedan',
  'Hatchback',
  'Coupe',
  'Truck',
  'Convertible',
  'Van',
  'Wagon',
];

export const FUEL_TYPES: FuelType[] = [
  'Petrol',
  'Diesel',
  'Hybrid',
  'Plug-in Hybrid',
  'Electric',
];

export const TRANSMISSION_TYPES: TransmissionType[] = [
  'Automatic',
  'Manual',
  'Dual-Clutch',
  'CVT',
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-001',
    title: '2024 Porsche 911 Carrera GTS',
    make: 'Porsche',
    model: '911 Carrera GTS',
    year: 2024,
    price: 158200,
    originalPrice: 165000,
    mileage: 1850,
    transmission: 'Dual-Clutch',
    fuelType: 'Petrol',
    bodyType: 'Coupe',
    condition: 'Brand New',
    engine: '3.0L Twin-Turbo Flat-6',
    horsepower: 473,
    drivetrain: 'RWD',
    exteriorColor: 'Chalk White',
    interiorColor: 'Black / Carmine Red Leather',
    vin: 'WP0AB2A98RS102948',
    description:
      'The 2024 Porsche 911 Carrera GTS blends extreme racetrack dynamics with exceptional daily livability. Equipped with Sport Chrono Package, Porsche Active Suspension Management (PASM) with sport suspension (-10 mm), and sports exhaust system.',
    features: [
      'Sport Chrono Package',
      'PASM Sport Suspension',
      'Burmester High-End Surround Sound',
      'Adaptive 18-Way Sport Seats Plus',
      'Carbon Fiber Interior Package',
      'Apple CarPlay & Android Auto Wireless',
      '360-Degree Surround View',
    ],
    images: [
      {
        id: 'img-1',
        url: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1400&q=80',
        isPrimary: true,
        caption: 'Front 3/4 Exterior Angle',
      },
      {
        id: 'img-2',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80',
        isPrimary: false,
        caption: 'Rear Aerodynamic Profile',
      },
      {
        id: 'img-3',
        url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1400&q=80',
        isPrimary: false,
        caption: 'Dashboard & Steering Cockpit',
      },
    ],
    featured: true,
    status: 'available',
    seller: {
      id: 'sel-101',
      name: 'Apex Motor Gallery',
      email: 'sales@apexmotors.com',
      phone: '+1 (555) 234-8901',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      isVerifiedDealer: true,
      rating: 4.9,
      totalReviews: 128,
      city: 'Los Angeles',
      state: 'CA',
    },
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-28T14:30:00Z',
  },
  {
    id: 'veh-002',
    title: '2023 Tesla Model S Plaid AWD',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2023,
    price: 89990,
    originalPrice: 94000,
    mileage: 8200,
    transmission: 'Automatic',
    fuelType: 'Electric',
    bodyType: 'Sedan',
    condition: 'Certified Pre-Owned',
    engine: 'Tri-Motor Electric All-Wheel Drive',
    horsepower: 1020,
    drivetrain: 'AWD',
    exteriorColor: 'Deep Blue Metallic',
    interiorColor: 'Cream Premium Interior',
    vin: '5YJSA1E67PF992811',
    description:
      'Tri-motor powertrain with torque vectoring capable of 0-60 mph in 1.99s. Comes with Full Self-Driving capability capability, 21-inch Arachnid wheels, and yoke steering wheel.',
    features: [
      'Full Self-Driving (FSD) Hardware 4.0',
      'Tri-Motor AWD 1,020 hp',
      'Yoke Steering Wheel',
      '22-Speaker 960W Audio System',
      'Ventilated Front Seats',
      'Panoramic All-Glass Roof',
      'Rear Seat Gaming Display',
    ],
    images: [
      {
        id: 'img-4',
        url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1400&q=80',
        isPrimary: true,
        caption: 'Exterior Front View',
      },
      {
        id: 'img-5',
        url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1400&q=80',
        isPrimary: false,
        caption: 'Minimalist Interior Cockpit',
      },
    ],
    featured: true,
    status: 'available',
    seller: {
      id: 'sel-102',
      name: 'Volt Luxury EV Center',
      email: 'contact@voltluxury.com',
      phone: '+1 (555) 789-1022',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
      isVerifiedDealer: true,
      rating: 4.8,
      totalReviews: 94,
      city: 'San Francisco',
      state: 'CA',
    },
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-29T11:20:00Z',
  },
  {
    id: 'veh-003',
    title: '2024 BMW X5 M60i xDrive',
    make: 'BMW',
    model: 'X5 M60i',
    year: 2024,
    price: 92400,
    mileage: 4300,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    bodyType: 'SUV',
    condition: 'Brand New',
    engine: '4.4L BMW M TwinPower Turbo V8 (48V Mild Hybrid)',
    horsepower: 523,
    drivetrain: 'AWD',
    exteriorColor: 'Brooklyn Grey Metallic',
    interiorColor: 'Tartufo Extended Merino Leather',
    vin: '5UXJU2C08R9A10245',
    description:
      'Combining robust M TwinPower Turbo V-8 performance with modern 48V mild hybrid efficiency and BMW Curved Display with iDrive 8.5 Operating System.',
    features: [
      'M Sport Package Pro',
      'Harman Kardon Surround Sound',
      'Panoramic Sky Lounge LED Roof',
      'Executive Package',
      'BMW Curved Display 14.9"',
      'Head-up Display',
    ],
    images: [
      {
        id: 'img-6',
        url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=80',
        isPrimary: true,
        caption: 'Exterior Front Elevation',
      },
      {
        id: 'img-7',
        url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=80',
        isPrimary: false,
        caption: 'Wheel & M Performance Brakes',
      },
    ],
    featured: true,
    status: 'available',
    seller: {
      id: 'sel-103',
      name: 'Bavarian Elite Auto',
      email: 'vip@bavarianelite.com',
      phone: '+1 (555) 456-7890',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      isVerifiedDealer: true,
      rating: 5.0,
      totalReviews: 210,
      city: 'Miami',
      state: 'FL',
    },
    createdAt: '2026-08-22T14:15:00Z',
    updatedAt: '2026-08-27T09:10:00Z',
  },
  {
    id: 'veh-004',
    title: '2023 Ford F-150 Lightning Platinum',
    make: 'Ford',
    model: 'F-150 Lightning',
    year: 2023,
    price: 74900,
    originalPrice: 81000,
    mileage: 12400,
    transmission: 'Automatic',
    fuelType: 'Electric',
    bodyType: 'Truck',
    condition: 'Used',
    engine: 'Dual eMotors Extended Range Battery',
    horsepower: 580,
    drivetrain: '4WD',
    exteriorColor: 'Agate Black Metallic',
    interiorColor: 'Black Nirvana Leather',
    vin: '1FT6W1EV7PW887612',
    description:
      'All-electric power with 775 lb-ft of instant torque. Features Pro Power Onboard 9.6kW, Ford BlueCruise hands-free driving, and Mega Power Frunk.',
    features: [
      'Pro Power Onboard 9.6kW',
      'Mega Power Frunk (400L)',
      'Ford BlueCruise 1.2',
      'B&O Unleashed 18-Speaker Audio',
      'Max Trailer Tow Package',
    ],
    images: [
      {
        id: 'img-8',
        url: 'https://images.unsplash.com/photo-1559416523-140ddc3d2a88?auto=format&fit=crop&w=1400&q=80',
        isPrimary: true,
        caption: 'Ford F-150 Lightning Truck Profile',
      },
    ],
    featured: false,
    status: 'available',
    seller: {
      id: 'sel-101',
      name: 'Apex Motor Gallery',
      email: 'sales@apexmotors.com',
      phone: '+1 (555) 234-8901',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      isVerifiedDealer: true,
      rating: 4.9,
      totalReviews: 128,
      city: 'Los Angeles',
      state: 'CA',
    },
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-29T16:00:00Z',
  },
];
